name: Java CI
 
on:
  push:
    branches: [ main ]  # Specify your target branch
  pull_request:
    branches: [ main ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Check out code
      uses: actions/checkout@v2
 
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Adjust to your project's Java version
 
    - name: Build with Maven
      run: mvn clean install
 
    - name: Run Tests with JaCoCo
      run: mvn test jacoco:report
 
    - name: Upload JaCoCo Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/  # Change this if your report path is different